=== juanfadev/LEW/XML/Tema 2/prerromanico.dtd
<!ELEMENT monuments (monument+)>
<!ELEMENT monument (name,type,year?,builders?,description, status?, location, gallery*, rating, visit, showed_by, bibliography)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT builders (builder+)>
<!ELEMENT builder (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT location (municipality, address?, coordenates)>
<!ELEMENT municipality (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT coordenates (latitude, longitude, altitude)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT altitude (#PCDATA)>
<!ELEMENT gallery (photo+| video+)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT visit (period+)>
<!ELEMENT period (day+)>
<!ELEMENT day (hour+)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT showed_by (#PCDATA)>
<!ELEMENT bibliography (website+)>
<!ELEMENT website (#PCDATA)>
<!ATTLIST monument id ID #REQUIRED>
<!ATTLIST period start CDATA #REQUIRED>
<!ATTLIST period end CDATA #REQUIRED>
<!ATTLIST day start CDATA #REQUIRED>
<!ATTLIST day end CDATA #REQUIRED>
<!ATTLIST hour start CDATA #REQUIRED>
<!ATTLIST hour end CDATA #REQUIRED>
<!ATTLIST photo uri CDATA #REQUIRED>
<!ATTLIST photo name CDATA #IMPLIED>
<!ATTLIST video uri CDATA #REQUIRED>
<!ATTLIST video name CDATA #IMPLIED>

=== juanfadev/LEW/XML/Tema 4/prerromanico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE monuments SYSTEM "prerromanico.dtd">
<monuments>
    <monument id="Naranco">
        <name>
            Santa María del Naranco
        </name>
        <type>
            Palacio
        </type>
        <year>
            845
        </year>
        <builders>
            <builder>San Miguel de Lillo</builder>
            <builder>Ramiro I</builder>
        </builders>
        <description>
            Se trata de un palacio de recreo de veinte metros de largo por unos seis de ancho y once de altura, construido con sillares pequeños muy bien escuadrados en hiladas horizontales, con dos naves superpuestas, cubiertas ambas por bóvedas de toba sobre arcos perpiaños, situado en un entorno en el que existían además la iglesia de San Miguel de Lillo y otra serie de edificios de servicio hoy desaparecidos. Este tipo de estructura era ya muy conocido en el arte prerrománico español, con antecedentes tan importantes como el Mausoleo de La Alberca, Santa Eulalia de Bóveda, la cripta de San Antolín de Palencia y, ya en el periodo asturiano, la Cámara Santa de la Catedral de Oviedo. Todos ellos eran edificios de doble bóveda y excepto en el primero, del que sólo quedan restos, en los demás nos ha llegado la nave inferior casi intacta, pero este es el único caso en que nos ha llegado también completa la superior, debido no sólo a que Asturias no sufrió invasiones ni estuvo en primera línea de alguna guerra como los tres primeros, sino también por su exquisita calidad de diseño y construcción, sorprendente en un edificio del siglo IX.
        </description>
        <status>
            Muy bueno
        </status>
        <location>
            <municipality>
                Oviedo (Asturias)
            </municipality>
            <address>
                Monte Naranco, s/n, 33012 Oviedo, Asturias
            </address>
            <coordenates>
                <latitude>43.379167</latitude>
                <longitude>-5.8682997</longitude>
                <altitude>527</altitude>
            </coordenates>
        </location>
        <gallery>
            <photo name="Santa María del Naranco Outside" uri="http://www.turismo-prerromanico.com/files/content/MSMNARANC/MSMNARANC3.jpg"/>
            <photo name="Santa María del Naranco Plano" uri="http://www.turismo-prerromanico.com/files/content/MSMNARANC/MSMNARANCPLAN2.jpg"/>
        </gallery>
        <rating>
            8.24
        </rating>
        <visit>
            <period start="1 Octubre" end="31 Marzo">
                <day start="Martes" end="Sabado">
                    <hour start="10:00:00" end="13:00:00"/>
                    <hour start="15:00:00" end="17:00:00"/>
                </day>
                <day start="Domingo" end="Lunes">
                    <hour start="10:00:00" end="13:00:00"/>
                </day>
            </period>
            <period start="1 Abril" end="30 Septiembre">
                <day start="Martes" end="Sabado">
                    <hour start="09:30:00" end="13:30:00"/>
                    <hour start="15:30:00" end="19:30:00"/>
                </day>
                <day start="Domingo" end="Lunes">
                    <hour start="10:00:00" end="13:00:00"/>
                </day>
            </period>
        </visit>
        <showed_by>
            Párroco
        </showed_by>
        <bibliography>
            <website>
                http://www.turismo-prerromanico.com/monumento/santa-maria-del-naranco-20130115191257/
            </website>
            <website>
                https://www.turismoasturias.es/descubre/cultura/prerromanico/santa-maria-del-naranco
            </website>
        </bibliography>
    </monument>
    <monument id="LosPrados">
        <name>
            Iglesia San Julián de los Prados
        </name>
        <type>
            Iglesia
        </type>
        <year>
            Siglo IX
        </year>
        <builders>
            <builder>Alfonso II</builder>
        </builders>
        <description>
            Construida a base de mampostería de piedras pequeñas con sillares en las esquinas, tiene planta basilical de tres naves separadas por arcos de medio punto en ladrillo sobre pilares cuadrados, con tres ábsides, pórtico a los pies y una gran nave de transepto, tan ancha y de mayor altura que la nave central, que tiene adosados un compartimento a cada lado. Esta nave está separada de la central por un muro en el que se abren un arco de triunfo y dos ventanas, estructura que nos recuerda una característica que ya encontramos en la fase de transición visigoda: la búsqueda de una forma de utilizar plantas basilicales añadiendo algún tipo de transepto, necesario por las características del culto en esa época. Su planta basilical, el pórtico de entrada, la carencia de torre de crucero, la búsqueda de una forma de separar las naves de la cabecera mediante un crucero atípico e incluso la sensación de horizontalidad que produce la relación de su anchura respecto a su altura, hacen que esta iglesia, aunque con grandes diferencias como la utilización de pilares en los arcos de separación de las naves y la forma del crucero y la cabecera, nos recuerde a San Juan de Baños y nos haga pensar en cómo consideraríamos la relación entre el arte asturiano y el visigodo si conociéramos algunos de los monumentos que existieron en las grandes ciudades en esa fase.
        </description>
        <status>
            Muy Bueno
        </status>
        <location>
            <municipality>
                Oviedo (Asturias)
            </municipality>
            <address>
                Plaza de Santullano, Oviedo
            </address>
            <coordenates>
                <latitude>43.3675</latitude>
                <longitude>-5.8394107</longitude>
                <altitude>570</altitude>
            </coordenates>
        </location>
        <gallery>
            <photo name="Exterior" uri="http://www.turismo-prerromanico.com/files/content/MSJPRADOS/MSJPRADOS1.jpg"/>
            <photo name="Plano" uri="http://www.turismo-prerromanico.com/files/content/MSJPRADOS/MSJPRADOSPLAN1.jpg"/>
        </gallery>
        <gallery>
            <video name="San Julian 1" uri="https://www.youtube.com/watch?v=fMCOnopVB6c"/>
            <video name="San Julian 2" uri="https://www.youtube.com/watch?v=U5jqWG97oUs"/>
        </gallery>
        <rating>
            7.2
        </rating>
        <visit>
            <period start="1 Octubre" end="30 Abril">
                <day start="Lunes" end="Sabado">
                    <hour start="10:00:00" end="12:30:00"/>
                    <hour start="15:00:00" end="17:00:00"/>
                </day>
            </period>
            <period start="1 Mayo" end="30 Junio">
                <day start="Martes" end="Sabado">
                    <hour start="10:00:00" end="12:30:00"/>
                    <hour start="16:00:00" end="18:00:00"/>
                </day>
                <day start="Lunes" end="Lunes">
                    <hour start="10:00:00" end="12:30:00"/>
                </day>
            </period>
            <period start="1 Julio" end="30 Septiembre">
                <day start="Martes" end="Viernes">
                    <hour start="09:30:00" end="13:00:00"/>
                    <hour start="16:00:00" end="18:00:00"/>
                </day>
                <day start="Lunes" end="Lunes">
                    <hour start="10:00:00" end="13:00:00"/>
                </day>
                <day start="Sabado" end="Sabado">
                    <hour start="09:30:00" end="12:30:00"/>
                </day>
            </period>
        </visit>
        <showed_by>
            Mª Isabel Díaz
        </showed_by>
        <bibliography>
            <website>https://www.turismoasturias.es/descubre/cultura/prerromanico/iglesia-de-san-julian-de-los-prados</website>
            <website>http://www.turismo-prerromanico.com/monumento/san-julin-de-los-prados-20130115114536/#ad-image-0</website>
        </bibliography>
    </monument>
    <monument id="CamaraSanta">
        <name>
            Cámara Santa
        </name>
        <type>
            Capillas
        </type>
        <year>
            Siglo IX
        </year>
        <builders>
            <builder>Alfonso II</builder>
        </builders>
        <description>
            La Cámara Santa de la Catedral de Oviedo luce luminosa y espléndida desde su última restauración, que ha hecho posible que desde el pasado catorce de abril muestre al público toda su belleza medieval, que la convierte en un símbolo de Asturias y en un significativo reclamo religioso, cultural y turístico.

            Fundada como capilla palatina por un rey asturiano, que la historia nombra como Alfonso II el Casto, y que vivió y amó en el siglo IX, la Cámara Santa de la Catedral de Oviedo ha sido testigo activo de miles de historias y avatares: punto de encuentro de peregrinos, devotos, viajeros, aventureros y hasta revolucionarios. Para todos ellos, de una u otra forma, ha sido referencia ineludible. Ha reído, sentido, llorado, latido, rezado, pensado al mismo tiempo que la Humanidad.
        </description>
        <status>
            Muy bueno
        </status>
        <location>
            <municipality>
                Oviedo (Asturias)
            </municipality>
            <address>
                Plaza Alfonso II El Casto S/N, 33003, Oviedo (Asturias)
            </address>
            <coordenates>
                <latitude>43.3622376</latitude>
                <longitude>-5.858409</longitude>
                <altitude>2737</altitude>
            </coordenates>
        </location>
        <gallery>
